create table agenda(apellido varchar(30),nombre varchar(20),domicilio varchar(30),telefono varchar(11));
decribe agenda;
insert into agenda(apellido,nombre,domicilio,telefono) values ( 'Ronan','Saoirse','Greystones','4234567');
insert into agenda (apellido,nombre,domicilio,telefono) values( 'Lerman','Logan','Beverly Hills','4458787');
insert into agenda (apellido,nombre,domicilio,telefono) values( 'Daddario','Alexandra','Upper East Side','4545454');
insert into agenda (apellido,nombre,domicilio,telefono) values( 'Bridges','Ludacris','Champaign','4545454');
insert into agenda (apellido,nombre,domicilio,telefono) values( 'Bridges','Ludacris','Champaign','4545454');
update agenda set nombre='Brian Ludacris' where nombre='Brian';
update agenda set telefono='4445566' where telefono='4545454';
update agenda set nombre='Brian Ludacris' where nombre='Brian';
